package com.google.android.gms.measurement.internal;

import android.content.Context;
import com.google.android.gms.common.util.VisibleForTesting;
import com.google.android.gms.internal.measurement.zzhe;
import com.google.android.gms.internal.measurement.zzho;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

@VisibleForTesting
public final class zzel {
    public static final zzek zzA = zza("measurement.upload.retry_time", 1800000L, 1800000L, zzbh.zza);
    public static final zzek zzB = zza("measurement.upload.retry_count", 6, 6, zzbj.zza);
    public static final zzek zzC = zza("measurement.upload.max_queue_time", 2419200000L, 2419200000L, zzbk.zza);
    public static final zzek zzD = zza("measurement.lifetimevalue.max_currency_tracked", 4, 4, zzbl.zza);
    public static final zzek zzE = zza("measurement.audience.filter_result_max_count", 200, 200, zzbn.zza);
    public static final zzek zzF = zza("measurement.upload.max_public_user_properties", 25, 25, (zzeh) null);
    public static final zzek zzG = zza("measurement.upload.max_event_name_cardinality", 500, 500, (zzeh) null);
    public static final zzek zzH = zza("measurement.upload.max_public_event_params", 25, 25, (zzeh) null);
    public static final zzek zzI = zza("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, zzbo.zza);
    public static final zzek zzJ;
    public static final zzek zzK = zza("measurement.test.string_flag", "---", "---", zzbq.zza);
    public static final zzek zzL = zza("measurement.test.long_flag", -1L, -1L, zzbr.zza);
    public static final zzek zzM = zza("measurement.test.int_flag", -2, -2, zzbs.zza);
    public static final zzek zzN;
    public static final zzek zzO = zza("measurement.experiment.max_ids", 50, 50, zzbv.zza);
    public static final zzek zzP = zza("measurement.max_bundles_per_iteration", 100, 100, zzbw.zza);
    public static final zzek zzQ = zza("measurement.sdk.attribution.cache.ttl", 604800000L, 604800000L, zzbx.zza);
    public static final zzek zzR = zza("measurement.redaction.app_instance_id.ttl", 7200000L, 7200000L, zzbz.zza);
    public static final zzek zzS;
    public static final zzek zzT;
    public static final zzek zzU;
    public static final zzek zzV;
    public static final zzek zzW;
    public static final zzek zzX;
    public static final zzek zzY;
    public static final zzek zzZ;
    public static final zzek zza = zza("measurement.ad_id_cache_time", 10000L, 10000L, zzax.zza);
    public static final zzek zzaA;
    public static final zzek zzaB;
    public static final zzek zzaC;
    public static final zzek zzaD;
    public static final zzek zzaE;
    public static final zzek zzaF;
    public static final zzek zzaG;
    public static final zzek zzaH;
    public static final zzek zzaI;
    public static final zzek zzaJ;
    public static final zzek zzaK;
    public static final zzek zzaL;
    public static final zzek zzaM;
    public static final zzek zzaN;
    /* access modifiers changed from: private */
    public static final List zzaO = Collections.synchronizedList(new ArrayList());
    private static final Set zzaP = Collections.synchronizedSet(new HashSet());
    public static final zzek zzaa;
    public static final zzek zzab;
    public static final zzek zzac;
    public static final zzek zzad;
    public static final zzek zzae;
    public static final zzek zzaf;
    public static final zzek zzag;
    public static final zzek zzah;
    public static final zzek zzai = zza("measurement.service.storage_consent_support_version", 203600, 203600, zzcs.zza);
    public static final zzek zzaj;
    public static final zzek zzak;
    public static final zzek zzal;
    public static final zzek zzam;
    public static final zzek zzan;
    public static final zzek zzao;
    public static final zzek zzap;
    public static final zzek zzaq;
    public static final zzek zzar;
    public static final zzek zzas;
    public static final zzek zzat;
    public static final zzek zzau;
    public static final zzek zzav;
    public static final zzek zzaw;
    public static final zzek zzax;
    public static final zzek zzay;
    public static final zzek zzaz;
    public static final zzek zzb = zza("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, zzbi.zza);
    public static final zzek zzc = zza("measurement.config.cache_time", 86400000L, 3600000L, zzba.zza);
    public static final zzek zzd = zza("measurement.config.url_scheme", "https", "https", zzbm.zza);
    public static final zzek zze = zza("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", zzby.zza);
    public static final zzek zzf = zza("measurement.upload.max_bundles", 100, 100, zzck.zza);
    public static final zzek zzg;
    public static final zzek zzh;
    public static final zzek zzi = zza("measurement.upload.max_events_per_bundle", 1000, 1000, zzdu.zza);
    public static final zzek zzj = zza("measurement.upload.max_events_per_day", 100000, 100000, zzee.zza);
    public static final zzek zzk = zza("measurement.upload.max_error_events_per_day", 1000, 1000, zzbt.zza);
    public static final zzek zzl = zza("measurement.upload.max_public_events_per_day", 50000, 50000, zzce.zza);
    public static final zzek zzm = zza("measurement.upload.max_conversions_per_day", 10000, 10000, zzcp.zza);
    public static final zzek zzn = zza("measurement.upload.max_realtime_events_per_day", 10, 10, zzda.zza);
    public static final zzek zzo = zza("measurement.store.max_stored_events_per_app", 100000, 100000, zzdl.zza);
    public static final zzek zzp = zza("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", zzdw.zza);
    public static final zzek zzq = zza("measurement.upload.backoff_period", 43200000L, 43200000L, zzef.zza);
    public static final zzek zzr = zza("measurement.upload.window_interval", 3600000L, 3600000L, zzeg.zza);
    public static final zzek zzs = zza("measurement.upload.interval", 3600000L, 3600000L, zzay.zza);
    public static final zzek zzt = zza("measurement.upload.realtime_upload_interval", 10000L, 10000L, zzaz.zza);
    public static final zzek zzu = zza("measurement.upload.debug_upload_interval", 1000L, 1000L, zzbb.zza);
    public static final zzek zzv = zza("measurement.upload.minimum_delay", 500L, 500L, zzbc.zza);
    public static final zzek zzw = zza("measurement.alarm_manager.minimum_interval", 60000L, 60000L, zzbd.zza);
    public static final zzek zzx = zza("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, zzbe.zza);
    public static final zzek zzy = zza("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, zzbf.zza);
    public static final zzek zzz = zza("measurement.upload.initial_upload_delay_time", 15000L, 15000L, zzbg.zza);

    static {
        Integer valueOf = Integer.valueOf(LZ4Constants.MAX_DISTANCE);
        zzg = zza("measurement.upload.max_batch_size", valueOf, valueOf, zzcw.zza);
        zzh = zza("measurement.upload.max_bundle_size", valueOf, valueOf, zzdi.zza);
        Boolean bool = Boolean.FALSE;
        zzJ = zza("measurement.test.boolean_flag", bool, bool, zzbp.zza);
        Double valueOf2 = Double.valueOf(-3.0d);
        zzN = zza("measurement.test.double_flag", valueOf2, valueOf2, zzbu.zza);
        Boolean bool2 = Boolean.TRUE;
        zzS = zza("measurement.validation.internal_limits_internal_event_params", bool2, bool2, zzca.zza);
        zzT = zza("measurement.collection.log_event_and_bundle_v2", bool2, bool2, zzcb.zza);
        zzU = zza("measurement.quality.checksum", bool, bool, (zzeh) null);
        zzV = zza("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", bool, bool, zzcc.zza);
        zzW = zza("measurement.audience.refresh_event_count_filters_timestamp", bool, bool, zzcd.zza);
        zzX = zza("measurement.audience.use_bundle_timestamp_for_event_count_filters", bool, bool, zzcf.zza);
        zzY = zza("measurement.sdk.collection.retrieve_deeplink_from_bow_2", bool2, bool2, zzcg.zza);
        zzZ = zza("measurement.sdk.collection.last_deep_link_referrer_campaign2", bool, bool, zzch.zza);
        zzaa = zza("measurement.lifecycle.app_in_background_parameter", bool, bool, zzci.zza);
        zzab = zza("measurement.integration.disable_firebase_instance_id", bool, bool, zzcj.zza);
        zzac = zza("measurement.collection.service.update_with_analytics_fix", bool, bool, zzcl.zza);
        zzad = zza("measurement.client.firebase_feature_rollout.v1.enable", bool2, bool2, zzcm.zza);
        zzae = zza("measurement.client.sessions.check_on_reset_and_enable2", bool2, bool2, zzcn.zza);
        zzaf = zza("measurement.scheduler.task_thread.cleanup_on_exit", bool, bool, zzco.zza);
        zzag = zza("measurement.collection.synthetic_data_mitigation", bool, bool, zzcq.zza);
        zzah = zza("measurement.androidId.delete_feature", bool2, bool2, zzcr.zza);
        zzaj = zza("measurement.client.click_identifier_control.dev", bool, bool, zzct.zza);
        zzak = zza("measurement.service.click_identifier_control", bool, bool, zzcu.zza);
        zzal = zza("measurement.client.consent.gmpappid_worker_thread_fix", bool2, bool2, zzcv.zza);
        zzam = zza("measurement.module.pixie.fix_array", bool2, bool2, zzcx.zza);
        zzan = zza("measurement.adid_zero.service", bool2, bool2, zzcy.zza);
        zzao = zza("measurement.adid_zero.remove_lair_if_adidzero_false", bool2, bool2, zzcz.zza);
        zzap = zza("measurement.adid_zero.remove_lair_if_userid_cleared", bool2, bool2, zzdb.zza);
        zzaq = zza("measurement.adid_zero.remove_lair_on_id_value_change_only", bool2, bool2, zzdc.zza);
        zzar = zza("measurement.adid_zero.adid_uid", bool2, bool2, zzdd.zza);
        zzas = zza("measurement.adid_zero.app_instance_id_fix", bool2, bool2, zzde.zza);
        zzat = zza("measurement.service.refactor.package_side_screen", bool2, bool2, zzdf.zza);
        zzau = zza("measurement.enhanced_campaign.service", bool2, bool2, zzdg.zza);
        zzav = zza("measurement.enhanced_campaign.client", bool2, bool2, zzdh.zza);
        zzaw = zza("measurement.enhanced_campaign.srsltid.client", bool, bool, zzdj.zza);
        zzax = zza("measurement.enhanced_campaign.srsltid.service", bool, bool, zzdk.zza);
        zzay = zza("measurement.service.store_null_safelist", bool2, bool2, zzdm.zza);
        zzaz = zza("measurement.service.store_safelist", bool2, bool2, zzdn.zza);
        zzaA = zza("measurement.redaction.no_aiid_in_config_request", bool2, bool2, zzdo.zza);
        zzaB = zza("measurement.redaction.config_redacted_fields", bool2, bool2, zzdp.zza);
        zzaC = zza("measurement.redaction.upload_redacted_fields", bool2, bool2, zzdq.zza);
        zzaD = zza("measurement.redaction.upload_subdomain_override", bool2, bool2, zzdr.zza);
        zzaE = zza("measurement.redaction.device_info", bool2, bool2, zzds.zza);
        zzaF = zza("measurement.redaction.user_id", bool2, bool2, zzdt.zza);
        zzaG = zza("measurement.redaction.google_signals", bool2, bool2, zzdv.zza);
        zzaH = zza("measurement.collection.enable_session_stitching_token.service", bool, bool, zzdx.zza);
        zzaI = zza("measurement.collection.enable_session_stitching_token.client.dev", bool, bool, zzdy.zza);
        zzaJ = zza("measurement.redaction.app_instance_id", bool2, bool2, zzdz.zza);
        zzaK = zza("measurement.redaction.populate_ephemeral_app_instance_id", bool2, bool2, zzea.zza);
        zzaL = zza("measurement.redaction.enhanced_uid", bool2, bool2, zzeb.zza);
        zzaM = zza("measurement.redaction.e_tag", bool2, bool2, zzec.zza);
        zzaN = zza("measurement.redaction.client_ephemeral_aiid_generation", bool2, bool2, zzed.zza);
    }

    @VisibleForTesting
    public static zzek zza(String str, Object obj, Object obj2, zzeh zzeh) {
        zzek zzek = new zzek(str, obj, obj2, zzeh, (zzej) null);
        zzaO.add(zzek);
        return zzek;
    }

    public static Map zzc(Context context) {
        zzhe zza2 = zzhe.zza(context.getContentResolver(), zzho.zza("com.google.android.gms.measurement"));
        return zza2 == null ? Collections.emptyMap() : zza2.zzc();
    }
}
